### ISSUE TITLE
significant regression change for quad curves

### ISSUE THREAD

**Issue by gojko** [rveciana/svg-path-properties#10]
Hi,

I just installed the new version and noticed a significant regression change for quad curves (this was correct, as in very similar to Chrome) in  0.2.1. One example curve is `M164,32Q164,409 347,375`

here it is with 0.2.1

```bash
$ npm install svg-path-properties@0.2.1
$ node
> var p = require('svg-path-properties')
> props = p.svgPathProperties('M164,32Q164,409 347,375')
> props.getTotalLength()
446.77680665424356
> props.getPointAtLength(props.getTotalLength() * 0.7)
{ x: 227.149522018377, y: 333.0980387286634 }
```

here it is with the 0.4.0 version

```bash
$ npm install svg-path-properties@0.4
$ node
> var p = require('svg-path-properties')
> props = p.svgPathProperties('M164,32Q164,409 347,375')
> props.getTotalLength()
186.1316738225926
> props.getPointAtLength(props.getTotalLength() * 0.7)
{ x: 292.1, y: 385.2 }
```

If it's of any use, here is a bunch of test cases pregenerated from Chrome (in the browser), with points along various paths in the curves -- we use that for internal testing and that's how this came out. Your (excellent) library was within 2 pixels of the Chrome calculations in older versions

[points.zip](https://github.com/rveciana/svg-path-properties/files/1171019/points.zip)

**Comment by rveciana** [comment]
Thank you for reporting this, I'll take a look. The point.zip file will be very useful, I'll add it to the tests.

**Comment by rveciana** [comment]
Hi, I'm looking at the json files and the values don't correspond to the ones I get from the browser. How did you get them?
The example point actually fails, I still have to find why.

**Comment by gojko** [comment]
I generated them from example svgs in chrome using this script, it goes through all the paths and generates points at 0.3 * length, 0.7 * length and 0.5 * length

```
ppath = function (path, pct) { 
    const svgp= path.getPointAtLength(path.getTotalLength() * pct); 
    return [svgp.x, svgp.y]; 
}; 
cases = []; 
for (entries of document.querySelectorAll('path').entries()) { 
  path = entries[1]; 
  cases.push({
     d: path.getAttribute('d'), 
    '0.5': ppath(path, 0.5), 
    '0.3': ppath(path, 0.3), 
    '0.7': ppath(path, 0.7)
  })
}; 
console.log(JSON.stringify(cases, null, 2));
```

**Comment by gojko** [comment]
I mentioned earlier, 0.2.1 was within 2 px of Chrome calculations, apart from a bug you fixed earlier (where quad curves degenerated into lines). we had a workaround to rewrite those into lines before passing to the function.

**Comment by rveciana** [comment]
Hi, I solved the problem for the issue. I will take a look at the json files now. It was the part where quad curves are ines, true. The check wasn't ok.
