### ISSUE TITLE
Wrong coordinates getPointAtLength

### ISSUE THREAD

**Issue by hugweb** [rveciana/svg-path-properties#11]
Hi guys !

I'm having a weird issue regarding the coordinates. I'm drawing a simple path in react native and moving a point following this path. I'm using the contentOffset value of my scrollView to generate the percentage value require by the **getPointAtLength** method. 

`svgWidth = width of the SVG`
`const properties = require("svg-path-properties").svgPathProperties(path)`
`const length = properties.getTotalLength()`
`const percentage = (value / svgWidth)  * length`
`const point = properties.getPointAtLength(pourcentage)`

Here is a visual of the rendering. I don't understand why my point is not following exactly the path.

![](https://media.giphy.com/media/xT1R9K8Drm5A3JYcQE/giphy.gif)

Any idea @rveciana ?

Best

**Comment by distributedlife** [comment]
I had a similar issue but it was caused by a transformed being applied in a G outside of my path. I had to reverse the transform after I had called **getPointAtLength**. Not sure if this helps you but it may help someone.

**Comment by jmuyskens** [comment]
I found a similar issue with an SVG path. I have a working example demonstrating that here: https://beta.observablehq.com/@jmuyskens/getpointatlength-browser-bug

**Comment by rveciana** [comment]
Thank you, that was useful. I'll take a look.

**Comment by rveciana** [comment]
All the Arc functions were buggy because of a library I was using to convert them into Bezier curves. I've found another one that seems to work:

https://beta.observablehq.com/@rveciana/tests-with-svg-path-arc-element

I'll add it into the code when I have some time

**Comment by rveciana** [comment]
The new v0.4.3 solves this issue

**Comment by animaonline** [comment]
Still getting the same problem, are you sure this has been fixed?

**Comment by rveciana** [comment]
Hi, can you please send me the path that is failing?

**Comment by animaonline** [comment]
It turns out the problem has something to do with the scrollview, I'm overlaying it with a circle svg, it works fine when its placed inside the parent svg though.

**Comment by rveciana** [comment]
Hi! Can you give me the path definition, please?

**Comment by edo1493** [comment]
HI @rveciana, what do you mean? :)

**Comment by rveciana** [comment]
Hi, I mean the letters and numbers defining the path, which is what you pass to the function as a parameter. Something like:

M482,50 A 500,500 0 1 0 723,144.6

**Comment by edo1493** [comment]
Dumb me.

`M375,196.49793084546508C359.375,172.2807295383785,343.75,148.0635282312919,328.125,127.92186433544859C312.5,107.78020043960528,296.875,91.71407395500529,281.25,120C265.625,148.2859260449947,250,220.92390461958405,234.375,231.378065894096C218.75,241.83222716860797,203.125,190.10257114304247,187.5,159.19790150985477C171.875,128.29323187666708,156.25,118.21354863585728,140.625,153.36746275300715C125,188.521376870157,109.37500000000001,268.90888834526646,93.75,280.333251953125C78.12499999999999,291.75761556098354,62.5,234.21883130159105,46.875,209.87742910473972C31.250000000000004,185.53602690788838,15.625000000000002,194.39200677357803,0,203.24798663926768`

**Comment by rveciana** [comment]
The path you sent me seems to work, and has a different shape from the one you posted before:
![svg-bug](https://user-images.githubusercontent.com/2832885/45997310-716b7180-c09f-11e8-9199-117f9c4f44e6.png)
