### ISSUE TITLE
Error for some pathstrings

### ISSUE THREAD

**Issue by chanind** [rveciana/svg-path-properties#12]
This library works fine most of the time, but I found a pathstring that causes this to throw an error and I'm not sure why. The pathstring is below:

`M 408 666 Q 408 569 276 440 Q 270 435 270 429 Q 269 427 270 426 Q 271 426 274 426 Q 347 445 443 578 Q 456 598 466 609 Q 472 616 470 623 Q 468 627 467 629 Q 447 666 431 670 L 408 666 Z`

This pathstring renders fine in the browser and as far as I can tell is valid. calling `getTotalLength` using this pathstring returns `NaN`. Any idea what the issue could be?

**Comment by rveciana** [comment]
Hi, the problem comes when adding 
 Q 468 627 467 629
I'm looking at the code.

**Comment by rveciana** [comment]
I think is solved. There was a division by zero at the getQuadraticArcLength function in your case.

**Comment by chanind** [comment]
Great, thanks!
