### ISSUE TITLE
I cannot use getTotalLength method.

### ISSUE THREAD

**Issue by hiroyaiizuka** [rveciana/svg-path-properties#17]
Browser: Google Chrome 
Editor: VScode 

I'm now creating SVG animation with scrolling effect. 
But I'm facing a trouble. 

When I code like below, there is an error.

`<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="css/styles.css" />
  </head>
  <body>
    <div class="container" id="container">
      <svg viewBox="0 0 288 175" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          class="line"
          　id="svgPath"
          d="M1 143.5C28.6 143.1 42.5 143.333 46
        143.5C52.3333 128.834 70.2 108.3 91 143.5H109L113.5 174.5L133.5 1L159.5
        174.5L167 143.5H201C208.167 134.5 227.5 121.9 247.5 143.5H287.5"
          stroke="black"
        />
      </svg>
    </div>

    <script>
      (function() {
        "use strict";

        window.onload = function() {
          const line = document.querySelector("line");

          const pathLength = line.getTotalLength();
          console.log(pathLength);
        };
      })();
    </script>
  </body>
</html>` 

Uncaught TypeError: Cannot read property  property 'getTotalLength' of null. 
Could you tell me the reason why this happens?

**Comment by meodai** [comment]
beacause a line is not a path. I think https://svgjs.com can do this

**Comment by rveciana** [comment]
@meodai  answer's correct. I close the issue

**Comment by ApoorvaJu08** [comment]
> beacause a line is not a path. I think https://svgjs.com can do this

Can you suggest some solution?

**Comment by rveciana** [comment]
To which problem?
The original problem was that the object was null. The solution is passing a valid object.

**Comment by ApoorvaJu08** [comment]
> To which problem?
> The original problem was that the object was null. The solution is passing a valid object.

I am having a multi line chart and I want to get length of each line using path.node().getTotalLength(). But it is not giving me the length.

**Comment by rveciana** [comment]
But do you get the `d` property? That's where you have the path. You could `console.log` the value for `path.node().getTotalLength()` and check if it's an svg path.
