### ISSUE TITLE
Browsers support

### ISSUE THREAD

**Issue by pandemozhno** [rveciana/svg-path-properties#19]
Hello. How Browsers support? It work in safari? In url write not work for safari SVG.someElement.getPointAtLength() ( https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement/getPointAtLength ). Please.

**Comment by rveciana** [comment]
The library replaces the browser functions, so it should work. Here you have en example on the browser:
http://bl.ocks.org/rveciana/209fa7efeb01f05fa4a544a76ac8ed91
