### ISSUE TITLE
Failing to parse path

### ISSUE THREAD

**Issue by filenwind** [rveciana/svg-path-properties#21]
The path: "M356,245c0,17.241,-13,31,-31,31s-31,-13,-31,-31s13,-31,31,-31S356,228,356,245z"

It will get the wrong shape if I collect all the points and draw as polyline.

Here is the example:  [https://codesandbox.io/s/p98oz63z7q](https://codesandbox.io/s/p98oz63z7q)

Thanks for your help!

**Comment by rveciana** [comment]
Hi @filenwind. I'm really sorry for the delay. The version 0.4.11 solves the issue. I was taking a wrong control point from the previous curve in the S part of the path.
