### ISSUE TITLE
getTangentAtLength() returns same value as getPointAtLength() for arcs in v0.4.3+

### ISSUE THREAD

**Issue by chrisparton1991** [rveciana/svg-path-properties#22]
First of all, thanks so much for all the effort you've put into this awesome library, appreciate it!

The `getTangentAtLength()` function is returning the same value as `getPointAtLength()` for arc paths for versions 0.4.3 and onwards.

I've got a CodeSandbox to reproduce the issue: https://codesandbox.io/s/svg-path-properties-gettangentatlength-issue-z0w36

v0.4.2 output is:
```
Line point: Object {x: 0, y: 0}
Line tangent: Object {x: 0.7071067811865475, y: 0.7071067811865475}

Arc point: Object {x: 0, y: 50.00000000000001}
Arc tangent: Object {x: 2.573102863976575e-16, y: 1} // Pass

Bezier point: Object {x: 100, y: 250}
Bezier tangent: Object {x: 0, y: -1}
```

v0.4.3+ output is:
```
Line point: Object {x: 0, y: 0}
Line tangent: Object {x: 0.7071067811865475, y: 0.7071067811865475}

Arc point: Object {x: 0, y: 50.00000000000001}
Arc tangent: Object {x: 0, y: 50.00000000000001} // Error, returning point data.

Bezier point: Object {x: 100, y: 250}
Bezier tangent: Object {x: 0, y: -1}
```

It looks like the issue crept in as part of commit e56e9ade8cdf471d7a6cf88bcad2895540cc8482, where `Arc.prototype.getTangentAtLength()` was updated. The code for the two methods is functionally identical after the change. Possibly the fix is as simple as reverting the changes to that method?

**Comment by rveciana** [comment]
Thank you! I'll take a look. I don't remember the changes I did...

**Comment by rveciana** [comment]
I think that the new version 0.4.10 solves the problem. Can you try it, please? Look at the attached pictures:

Before:
![Screenshot_2019-06-18 Screenshot(1)](https://user-images.githubusercontent.com/2832885/59668693-35da7f80-91b9-11e9-8bea-db7969519a66.png)
After:
![Screenshot_2019-06-18 Screenshot](https://user-images.githubusercontent.com/2832885/59668702-3a069d00-91b9-11e9-8f07-afcc1b086c33.png)

**Comment by chrisparton1991** [comment]
Thanks for getting the new release out so quickly, it's looking good now :)

**Comment by chrisparton1991** [comment]
I'll be using your library to implement a previewer for my LED sequencing software, https://github.com/sparkled/sparkled.

With your fix in place I've got my LEDs following a path beautifully: https://codesandbox.io/s/p9oxt. Thanks again!

**Comment by rveciana** [comment]
Cool! I never thought of these applications, it's fantastic.

**Comment by rveciana** [comment]
By the way, I solved another problem, so the good version is 0.4.11

**Comment by chrisparton1991** [comment]
Ah thanks, I'll be sure to update 👍 

At some point I might port this library across to Java so I can have the same functionality on my backend. If I do that, I'll be sure to credit you (and those you've credited) and let you know :)
