### ISSUE TITLE
Inconsistency with normal direction in getTangentAtLength()

### ISSUE THREAD

**Issue by eltapir** [rveciana/svg-path-properties#28]
There is an inconsistency (unless you like it this way) with the tangent/normal direction in getTangentAtLength() when using arcs and lines. I put a codepen to make the issue more clear.

link to codepen:
[https://codepen.io/krisheyse/pen/XWbGREV?editors=1111](url)

This is easy to fix in linear.ts @ line 39 (in version 1.0.3)

change:
`return { x: (this.x1 - this.x0) / module, y: (this.y1 - this.y0) / module };`

to:
`return { x: -(this.x1 - this.x0) / module, y: -(this.y1 - this.y0) / module };`

**Comment by eltapir** [comment]
Not solved/changed yet ;-)

**Comment by rveciana** [comment]
I tmakes many tests to fail... Taking a look

**Comment by rveciana** [comment]
Finally understood and done
