### ISSUE TITLE
empty paths?

### ISSUE THREAD

**Issue by Fil** [rveciana/svg-path-properties#35]
The DOM SVG interface allows paths with a null or `""` d attribute, this library will throw an error.

I can bypass this in my application by doing `new svgPathProperties(path || "M0,0")`, but I'm wondering what motivates this choice, or if it can be changed to bring it closer to the DOM API.

thank you!

**Comment by rveciana** [comment]
Oh, I didn't know that. It's an issue, sure. I'll try to solve it ASAP.

**Comment by rveciana** [comment]
Version 1.0.7 should solve the issue

**Comment by Fil** [comment]
thanks! works for "", but still breaks on `null`

**Comment by rveciana** [comment]
Oh, ok. I'll add it too.

**Comment by rveciana** [comment]
Version 1.0.8 should accept null as the value for the path

**Comment by Fil** [comment]
Perfect!

**Comment by Fil** [comment]
`new svgPathProperties(null).getPointAtLength(0) // Error: Wrong function at this part.`

**Comment by rveciana** [comment]
Solved in v1.0.9. The "single point paths" are now handled. If the point has some coordinates, the position is the point and tangent is 0,0.
Thanks a lot for your QA job!
