### ISSUE TITLE
sample a path?

### ISSUE THREAD

**Issue by Fil** [rveciana/svg-path-properties#37]
It would be great to have a method that returned n points well-spaced along a path—at regular intervals, or for some applications, depending on the local curvature.

We can currently call `l = getTotalLength()` then `for (i…l) getPointAtLength(i)`; In my tests svg-path-properties is about 2x faster than native svg.

But I suspect (I haven't tried it yet) that it could be much much faster to sample the whole path at once? <del>[EDIT: wrong!] In theory for this particular task, it should even be n/2 times faster, where n is the number of samples—since we wouldn't have to walk the path from start for each point.</del>

The application I have in mind at the moment is to extract many points from many paths, in order to compute a "voronoi of paths". See https://observablehq.com/d/7357e870269117c0 (not finished, but it should give an idea).

**Comment by rveciana** [comment]
I'll take a look. I'm not sure that it will be much faster since the class has the path parsed and it's quite fast querying it more than once. But I agree that the method would be convenient.

**Comment by Fil** [comment]
Ah yes I hadn't read https://github.com/rveciana/svg-path-properties/blob/master/src/svg-path-properties.ts#L341 — this could be slightly improved by bisection but I don't think it will bring a lot of performance :(. Maybe it's not worth the effort since it would mean a departure from the original API.

**Comment by rveciana** [comment]
Yes, the getPartAtLength could be improved knowing the previous point part, since it has to be the same or further. Even with this, the length for each part is also stored, so unless there are a lot of parts in the path, the search is quite fast. 
I think I can let it as it is unless you see a way that really improves the efficiency.
