### ISSUE TITLE
Error getting point along quadratic path if it is a straight line

### ISSUE THREAD

**Issue by will-hart** [rveciana/svg-path-properties#4]
I have the following path string, which just happens to be a straight line:

    M500,300 Q425,325 350,350

I then use the path as follows (version `0.1.2`):

    let pathData = svgPathProperties("M500,300 Q425,325 350,350")
    const pathLen = pathData.getTotalLength()
    let pos = pathData.getPointAtLength(0)

I get an exception on the `getPointAtLength()` call:

    Uncaught TypeError: Cannot read property 'getPointAtLength' of undefined
        at Function.svgProperties.getPointAtLength (path-properties.js:501)

The state that causes the error looks like this:

![Error state](https://cloud.githubusercontent.com/assets/391950/23335638/6f108bf8-fc0d-11e6-8e3b-16a8421fd281.png)

It looks like the partial length is `NaN`

![NaN Partial Length](https://cloud.githubusercontent.com/assets/391950/23335661/227bcbe4-fc0e-11e6-9bbc-c7a4d98564c8.png)

This is because `getQuadraticArcLength` is returning NaN as `ax` and `ay` are both zero.

![getQuadraticArcLength](https://cloud.githubusercontent.com/assets/391950/23335746/d984d92e-fc0f-11e6-9009-edf4de85f1ae.png)

I was able to fix this by adding to the `getQuadraticArcLength` method after `ax` and `ay` are determined:

    if (ax === 0 && ay === 0) {
        return t * Math.sqrt(Math.pow(xs[2] - xs[0], 2) + Math.pow(ys[2] - ys[0], 2));
    }

However I'm not sure if this will result in any side effects? 

Awesome library by the way :)

**Comment by rveciana** [comment]
Thanks a lot for reporting the bug.
Now (v0.1.3) it works and the tests are still running properly.

**Comment by will-hart** [comment]
Great! Thanks :)
