### ISSUE TITLE
Eslint "Unable to resolve path to module 'svg-path-properties'"

### ISSUE THREAD

**Issue by reinismu** [rveciana/svg-path-properties#47]
We encountered linter issue when adding `svg-path-properties` package to our project.

> error  Unable to resolve path to module 'svg-path-properties'  import/no-unresolved

I did a bit of debugging and it turns out that `"jsnext:main": "dist/index",` (https://github.com/rveciana/svg-path-properties/blob/master/package.json#L16) is causing issues with `import/no-unresolved`

Under the hood eslint uses `resolve` package and this function https://github.com/browserify/resolve/blob/master/lib/sync.js#L157
It tries to parse out `main`. In our case it gets incorrect one `"jsnext:main": "dist/index",` instead of `"main": "dist/svg-path-properties.cjs.js",`. Because of this linter fails.

Issue in resolve that seemed related: https://github.com/browserify/resolve/issues/93

Could you remove `"jsnext:main": "dist/index",`?

**Comment by rveciana** [comment]
Done, thanks. I don't think many people is using it with this option.
