### ISSUE TITLE
.getSegmentAtLength()?

### ISSUE THREAD

**Issue by veltman** [rveciana/svg-path-properties#6]
One thing that would be really useful is the ability to get the segment that a point is on, which is being calculated internally anyway.  I'd imagine something like:

```js
svgProperties.getSegmentAtLength = function(fractionLength){
  var fractionPart = getPartAtLength(fractionLength),
      start = functions[fractionPart.i].getPointAtLength(0),
      end = functions[fractionPart.i].getPointAtLength(partial_lengths[fractionPart.i] - partial_lengths[fractionPart.i - 1]);
  return {
    i: fractionPart.i,
    x1: start.x,
    y1: start.y,
    x2: end.x,
    y2: end.y
  };
};
```

Rather than double-dipping into `getPartAtLength()` over and over another possibility that would be great for iterating over a path is simply returning the `i` index in `getPointAtLength()` and a `getSegmentNumber()` function that takes the index and returns its start and end points. That way, if multiple points are on the same segment, you don't keep looking it up.

But I'm not sure what makes the most sense. What do you think?

**Comment by rveciana** [comment]
But this assumes that all points are on segments, and they can be on a Bézier curve. Or am I understanding it wrongly?
Returning the part would be nice. And returning the curve between two points would be nice too...

**Comment by veltman** [comment]
I meant segments as in any fraction of the path, not just line segments, a la `getPathSegAtLength()`.  For my purposes I only care about the start and end points, but it could certainly return a lot of additional information about the segment, like its length and its command.

**Comment by rveciana** [comment]
OK, sounds interesting, I'll try to do it.

**Comment by veltman** [comment]
I'm happy to give it a shot and send a PR. But is there other information you'd want included in the result besides the starting x,y, ending x,y, and index?

**Comment by rveciana** [comment]
We could start with this. If we add more things later, it won't be a
problem.

Thank you


El dia 12/06/2017 9:37 p. m., "Noah Veltman" <notifications@github.com> va
escriure:

**Comment by veltman** [comment]
I'm thinking what might make sense is `properties.getParts()`, which returns an array of:

```js
[
  { start: { x: 0, y: 0, ... }, end: { x: 100, y: 50, ... }, length: ..., getPointAtLength: ..., getTangentAtLength: ..., getPropertiesAtLength: ... },
  ...
]
```

Where `start` is the equivalent of calling `getPropertiesAtLength()` on the length at the beginning of the part, `end` is the same for the length at the end of the part, length is the partial length, and `getPointAtLength`, `getTangentAtLength`, `getPropertiesAtLength` are the functions for that part.

This would allow lots of flexibility for iterating over stuff.

`properties.getPartAtLength(l)` would return just the one element from the array for a given length.

How does that sound?

**Comment by rveciana** [comment]
I made the function, you can check it here: https://github.com/rveciana/svg-path-properties/tree/getparts

If it's what you were looking for, I'll merge it.

**Comment by rveciana** [comment]
I have added the function at the 0.4.0 version
