### ISSUE TITLE
Incorrect path lengths for multiple movetos

### ISSUE THREAD

**Issue by veltman** [rveciana/svg-path-properties#7]
While working on #6 I came across another possible bug, where a `moveto` adds to the length. For example, a single path string with two rectangles in it treats the gap between the two rectangles as part of the path, and allows you to get a point in that empty space:

https://runkit.com/590ff00e90d6f10011380a19/5940094cad6d1900120ea30b

**Comment by veltman** [comment]
I think the issue is this line:

https://github.com/rveciana/svg-path-properties/blob/master/src/path-properties.js#L54

which assumes that parsed[0] is the starting point, which is only true if there aren't additional `moveto`s. Will submit a patch.

**Comment by rveciana** [comment]
Thank you! I'm out gir some days, but when I'm Jack, I'll look all t'he
issues.


El dia 13/06/2017 18:05, "Noah Veltman" <notifications@github.com> va
escriure:
